# Interactive first-run setup for Work Assistant (Windows).
# Usage: powershell -ExecutionPolicy Bypass -File setup.ps1

$ErrorActionPreference = "Stop"
$AgentDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $AgentDir

Write-Host ""
Write-Host "Work Assistant — Setup" -ForegroundColor Cyan
Write-Host "Installs dependencies, configures LLM, and creates an Obsidian vault." -ForegroundColor DarkGray
Write-Host ""

function Read-Default {
    param([string]$Prompt, [string]$Default)
    $input = Read-Host "$Prompt [$Default]"
    if ([string]::IsNullOrWhiteSpace($input)) { return $Default }
    return $input
}

# ─── LLM ───
Write-Host "Step 1 — LLM backend" -ForegroundColor Cyan
Write-Host "  1) anthropic"
Write-Host "  2) openai"
Write-Host "  3) ollama"
$choice = Read-Default "Provider (1-3)" "1"
$provider = @{ "1" = "anthropic"; "2" = "openai"; "3" = "ollama" }[$choice]
if (-not $provider) { $provider = "anthropic" }

$apiKeyEnv = ""
$apiKey = ""
switch ($provider) {
    "anthropic" { $apiKeyEnv = "ANTHROPIC_API_KEY"; $defaultModel = "claude-sonnet-4-20250514" }
    "openai"    { $apiKeyEnv = "OPENAI_API_KEY"; $defaultModel = "gpt-4o" }
    "ollama"    { $apiKeyEnv = ""; $defaultModel = "llama3.1:latest" }
}

if ($provider -ne "ollama") {
    $secure = Read-Host "Enter $apiKeyEnv" -AsSecureString
    $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    $apiKey = [Runtime.InteropServices.Marshal]::PtrToStringAuto($ptr)
}

$model = Read-Default "Model name" $defaultModel

# ─── Identity ───
Write-Host ""
Write-Host "Step 2 — Assistant identity" -ForegroundColor Cyan
$assistantName = Read-Default "Assistant display name" "Work Assistant"
$roleDesc = Read-Default "Your role" "Product Manager"
$timezone = Read-Default "Timezone (IANA)" "America/New_York"

# ─── Vault ───
Write-Host ""
Write-Host "Step 3 — Obsidian vault" -ForegroundColor Cyan
$parentDir = Split-Path -Parent $AgentDir
$defaultVault = Join-Path $parentDir "WorkVault"
$vaultPath = Read-Default "Vault path" $defaultVault
New-Item -ItemType Directory -Force -Path $vaultPath | Out-Null

# ─── Python venv ───
Write-Host ""
Write-Host "Step 4 — Python environment" -ForegroundColor Cyan
$venv = Join-Path $AgentDir ".venv"
if (-not (Test-Path $venv)) {
    python -m venv $venv
}
& "$venv\Scripts\pip.exe" install -q -r requirements.txt
Write-Host "Dependencies installed." -ForegroundColor Green

# ─── .env ───
if ($apiKey) {
    @"
# Work Assistant — generated by setup.ps1
`$env:$apiKeyEnv = "$apiKey"
"@ | Set-Content -Path (Join-Path $AgentDir ".env.ps1") -Encoding UTF8
    Write-Host "Wrote .env.ps1 (dot-source before running: . .\.env.ps1)" -ForegroundColor Green
}

# ─── Seed vault ───
$memory = Join-Path $vaultPath "agent-memory"
$inbox = Join-Path $vaultPath "inbox"
$daily = Join-Path $vaultPath "daily"
foreach ($d in @($memory, $inbox, $daily)) { New-Item -ItemType Directory -Force -Path $d | Out-Null }

$seedFiles = @{
    "daily.md"      = "# Daily Memory`n`n*Auto-managed by Work Assistant.*`n"
    "weekly.md"     = "# Weekly Memory`n`n*Auto-managed by Work Assistant.*`n"
    "sprintly.md"   = "# Sprintly Memory`n`n*Auto-managed by Work Assistant.*`n"
    "monthly.md"    = "# Monthly Memory`n`n*Auto-managed by Work Assistant.*`n"
    "quarterly.md"  = "# Quarterly Memory`n`n*Auto-managed by Work Assistant.*`n"
    "tasks.md"      = "# Tasks`n`nNo open tasks yet.`n"
    "heartbeat.md"  = "# Standing Questions`n`n- [ ] Example standing question`n"
    "decisions.md"  = "# Decisions Log`n`n---`n`n"
    "experiments.md"= "# Experiment Log`n`n---`n`n"
}
foreach ($name in $seedFiles.Keys) {
    $path = Join-Path $memory $name
    if (-not (Test-Path $path)) { $seedFiles[$name] | Set-Content -Path $path -Encoding UTF8 }
}

# ─── people.yaml ───
$people = Join-Path $AgentDir "people.yaml"
if (-not (Test-Path $people)) {
    Copy-Item (Join-Path $AgentDir "people.example.yaml") $people
}

# ─── config.yaml via Python ───
$env:SETUP_PROVIDER = $provider
$env:SETUP_MODEL = $model
$env:SETUP_API_KEY_ENV = $apiKeyEnv
$env:SETUP_ASSISTANT_NAME = $assistantName
$env:SETUP_ROLE_DESC = $roleDesc
$env:SETUP_TIMEZONE = $timezone
$env:SETUP_VAULT_PATH = $vaultPath
$env:AGENT_DIR = $AgentDir

$pyScript = @'
import os, yaml
from pathlib import Path
agent_dir = Path(os.environ["AGENT_DIR"])
vault_path = str(Path(os.environ["SETUP_VAULT_PATH"]).expanduser())
provider = os.environ["SETUP_PROVIDER"]
llm = {"provider": provider, "model": os.environ["SETUP_MODEL"], "temperature": 0.4, "max_tokens": 20000, "max_chars_per_source": 12000}
if os.environ.get("SETUP_API_KEY_ENV"):
    llm["api_key_env"] = os.environ["SETUP_API_KEY_ENV"]
if provider == "ollama":
    llm["base_url"] = "http://localhost:11434"
config = {
    "assistant": {"name": os.environ["SETUP_ASSISTANT_NAME"], "id": "work-assistant", "role_description": os.environ["SETUP_ROLE_DESC"]},
    "llm": llm,
    "templates": {"directory": "templates", "domain_rules": "templates/domain/jira_rules.md"},
    "sources": {
        "slack": {"enabled": False}, "gmail": {"enabled": False}, "jira": {"enabled": False},
        "confluence": {"enabled": False}, "meetings": {"enabled": False},
        "obsidian": {"enabled": True, "vault_path": vault_path, "watch_folders": ["inbox", "daily"], "recency_minutes": 160, "memory_folder": "agent-memory", "memory_extra_files": []},
        "taskflow": {"enabled": False},
    },
    "agent": {"state_db": "~/.config/work-assistant/state.db", "log_file": "~/.config/work-assistant/agent.log", "timezone": os.environ["SETUP_TIMEZONE"], "max_chars_per_source": 8000},
}
with open(agent_dir / "config.yaml", "w", encoding="utf-8") as f:
    yaml.dump(config, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
print("Wrote config.yaml")
'@

& "$venv\Scripts\python.exe" -c $pyScript

Write-Host ""
Write-Host "Setup complete!" -ForegroundColor Green
Write-Host "  Vault:  $vaultPath"
Write-Host "  Config: $(Join-Path $AgentDir 'config.yaml')"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Open Obsidian -> Open folder as vault -> $vaultPath"
Write-Host "  2. .\.venv\Scripts\Activate.ps1"
if ($apiKey) { Write-Host "  3. . .\.env.ps1" }
Write-Host "  4. python main.py --dry-run"
Write-Host ""
